# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a591545ffb80da21f77d654ec8f7f031854881555f02867252dbac862e4a0e4119915f151fcbdf29d4dcd29d256a278954f1a3bed8e292f1693d424f0684e69

test:
  secret_key_base: b0a2bb0692ff7b8c4d463e74afd48f3ddbad40ddc3173d013a9befb9dad5157cbc54a3eac47bfd75c777e8c01b6e020aaeb1b6b4ad7b9a783c52e7bf04b04fcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
